# Generated by Django 5.2 on 2025-04-15 18:36

import counter.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.ImageField(upload_to=counter.models.upload_to_original)),
                ('yolo_processed_file', models.ImageField(blank=True, null=True, upload_to=counter.models.upload_to_yolo)),
                ('hog_processed_file', models.ImageField(blank=True, null=True, upload_to=counter.models.upload_to_hog)),
                ('yolo_people_counted', models.IntegerField(blank=True, null=True)),
                ('hog_people_counted', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
