# Generated by Django 5.2 on 2025-04-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeopleDetection',
            new_name='PeopleCounting',
        ),
    ]
